.catalog:
  name: springboot1
  description: |
     my-catalog  -sprinboot1
  version: 0.1
  minimum_rancher_version: v1.0.0
  maintainer: "samwongcn@qq.com"
  questions:
    - variable: "scale_number"
      description: |
        Scale Number 
      label: "Nginx Scale Number:"
      default: "1"
      required: true
      type: "int"
    - variable: "ext_port"
      description: |
        External Port
      label: "HAProxy External Port:"
      default: "9005"
      required: true
      type: "int"

version: '2'
services:
  springboot:
    scale: $scale_number
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: tcp
        service: nginx
        source_port: $ext_port
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
